theme: jekyll-theme-cayman
title: MaxFLO
description: "A project that parallelizes 2 max flow algorithms, Dinic's and Push-Relabel.\nKatia Villevald and Wynne Yao."
github:
  repository_url: https://github.com/KatiaVi/418MaxFloProject
